# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{solusvm}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin Mazzi"]
  s.date = %q{2010-06-18}
  s.description = %q{A gem for interacting with the SolusVM API}
  s.email = %q{jmazzi@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "lib/solusvm.rb",
     "lib/solusvm/base.rb",
     "lib/solusvm/client.rb",
     "lib/solusvm/exceptions.rb",
     "lib/solusvm/general.rb",
     "lib/solusvm/hash.rb",
     "lib/solusvm/server.rb",
     "test/helper.rb",
     "test/test_solusvm.rb"
  ]
  s.homepage = %q{http://github.com/jmazzi/solusvm}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A gem for interacting with the SolusVM API}
  s.test_files = [
    "test/helper.rb",
     "test/test_solusvm.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

