# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{solusvm}
  s.version = "0.7.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin Mazzi"]
  s.date = %q{2010-08-31}
  s.default_executable = %q{solusvm}
  s.description = %q{Solusvm allows for easy interaction with the SolusVM Admin::API.}
  s.email = %q{jmazzi@gmail.com}
  s.executables = ["solusvm"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION.yml",
     "bin/solusvm",
     "lib/solusvm.rb",
     "lib/solusvm/base.rb",
     "lib/solusvm/client.rb",
     "lib/solusvm/exceptions.rb",
     "lib/solusvm/general.rb",
     "lib/solusvm/hash.rb",
     "lib/solusvm/server.rb",
     "solusvm.gemspec",
     "test/fixtures/base_bad_key.txt",
     "test/fixtures/base_node_does_not_exist.txt",
     "test/fixtures/base_unauthorized_ip.txt",
     "test/fixtures/client_authenticate_error.txt",
     "test/fixtures/client_authenticate_success.txt",
     "test/fixtures/client_change_password_error.txt",
     "test/fixtures/client_change_password_success.txt",
     "test/fixtures/client_create_error.txt",
     "test/fixtures/client_create_success.txt",
     "test/fixtures/client_exists_success.txt",
     "test/fixtures/error.txt",
     "test/fixtures/general_node_list_all_ips_available.txt",
     "test/fixtures/general_node_list_all_ips_not_available.txt",
     "test/fixtures/general_node_statistics_success.txt",
     "test/fixtures/general_nodes_success.txt",
     "test/fixtures/general_templates_success.txt",
     "test/fixtures/server_boot_success.txt",
     "test/fixtures/server_create_success.txt",
     "test/fixtures/server_exists_success.txt",
     "test/fixtures/server_reboot_success.txt",
     "test/fixtures/server_resume_success.txt",
     "test/fixtures/server_shutdown_success.txt",
     "test/fixtures/server_suspend_success.txt",
     "test/fixtures/server_terminate_success.txt",
     "test/helper.rb",
     "test/test_base.rb",
     "test/test_client.rb",
     "test/test_general.rb",
     "test/test_hash.rb",
     "test/test_server.rb",
     "test/test_solusvm.rb"
  ]
  s.homepage = %q{http://github.com/site5/solusvm}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{solusvm}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Wrapper for the SolusVM Admin::API}
  s.test_files = [
    "test/helper.rb",
     "test/test_base.rb",
     "test/test_client.rb",
     "test/test_general.rb",
     "test/test_hash.rb",
     "test/test_server.rb",
     "test/test_solusvm.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<xml-simple>, [">= 0"])
    else
      s.add_dependency(%q<xml-simple>, [">= 0"])
    end
  else
    s.add_dependency(%q<xml-simple>, [">= 0"])
  end
end

